name: kkw_blog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  markdown: ^7.2.2
  responsive_builder: ^0.7.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.6.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GmarketSans
      fonts:
        - asset: fonts/GmarketSansTTFBold.ttf
        - asset: fonts/GmarketSansTTFLight.ttf
        - asset: fonts/GmarketSansTTFMedium.ttf

flutter_intl: 
  enabled: true 
  class_name: Messages 
  main_locale: ko
  arb_dir: lib/resource/l10n/arb 
  output_dir: lib/resource/l10n/generated